### ISSUE TITLE
ideviceInstaller error on Mac with Genium-Framework Api usage

### ISSUE THREAD

**Issue by tovaibhav1** [Genium-Framework/Appium-Support#6]
Using methods as:

```
          ServerArguments serverArguments = new ServerArguments();
    serverArguments.setArgument("--address", "127.0.0.1");
    serverArguments.setArgument("--no-reset", true);
    serverArguments.setArgument("--local-timezone", true);
    serverArguments.setArgument("--port", "4723");
    serverArguments.setArgument("--session-override", true);
    serverArguments.setArgument("--log", properties.get("appiumLogs"));
    AppiumServer _appiumServer = new AppiumServer(serverArguments);
    _appiumServer.startServer();
```

**Works fine for Windows machine, but for Mac, its giving error as below. Howerver if Appium GUI**
**is started manually i.e. without API usage than tests run fine.**
**Appium v: 1.4.13**
**Mac: 0.10.5**

2016-01-20 10:39:21:571 - info: Welcome to Appium v1.4.13 (REV c75d8adcb66a75818a542fe1891a34260c21f76a)
2016-01-20 10:39:21:574 - info: Appium REST http interface listener started on 127.0.0.1:4723
2016-01-20 10:39:21:577 - info: [debug] Non-default server args: {"address":"127.0.0.1","sessionOverride":true,"noReset":true,"log":"/Users/intelligrape/appiumLogs.log","localTimezone":true}
2016-01-20 10:39:21:577 - info: Console LogLevel: debug
2016-01-20 10:39:21:577 - info: File LogLevel: debug
2016-01-20 10:39:22:338 - info: --> GET /wd/hub/status {}
2016-01-20 10:39:22:340 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-01-20 10:39:22:350 - info: <-- GET /wd/hub/status 200 6.830 ms - 105 {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}
2016-01-20 10:39:23:185 - info: --> POST /wd/hub/session {"desiredCapabilities":{"platformVersion":"8.1.3","app":"/Users/intelligrape/Mobility_QA/app/American-Swan.ipa","platformName":"iOS","deviceName":"TTND iPhone5c 1","browserName":"iOS","--log":"/Users/intelligrape/appiumLogs.log","udid":"adff85c69b6404975219f5518d32571545c7b421","takesScreenshot":"true","noReset":true}}
2016-01-20 10:39:23:185 - info: Client User-Agent string: Apache-HttpClient/4.3.3 (java 1.5)
2016-01-20 10:39:23:186 - warn: Converting cap takesScreenshot from string to boolean. This might cause unexpected behavior.
2016-01-20 10:39:23:187 - info: [debug] The following desired capabilities were provided, but not recognized by appium. They will be passed on to any other services running on this server. : --log, takesScreenshot
2016-01-20 10:39:23:189 - info: [debug] Using local .ipa from desired caps: /Users/intelligrape/Mobility_QA/app/American-Swan.ipa
2016-01-20 10:39:23:189 - info: [debug] Copying local zip to tmp dir
2016-01-20 10:39:23:402 - info: [debug] /Users/intelligrape/Mobility_QA/app/American-Swan.ipa copied to /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/appium-app.zip
2016-01-20 10:39:23:535 - info: [debug] Unzipping /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/appium-app.zip
2016-01-20 10:39:23:535 - info: [debug] Testing zip archive: /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/appium-app.zip
2016-01-20 10:39:23:945 - info: [debug] Zip archive tested clean
2016-01-20 10:39:24:482 - info: [debug] Unzip successful
2016-01-20 10:39:24:483 - info: [debug] Using locally extracted app: /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/Payload/American-Swan.app
2016-01-20 10:39:24:483 - info: [debug] Creating new appium session 6708fa84-72ec-41c2-955d-e3f22ebd77b9
2016-01-20 10:39:24:485 - info: [debug] Removing any remaining instruments sockets
2016-01-20 10:39:24:486 - info: [debug] Cleaned up instruments socket /tmp/instruments_sock
2016-01-20 10:39:24:486 - info: [debug] Auto-detecting iOS udid...
2016-01-20 10:39:24:486 - info: [debug] Not auto-detecting udid, running on sim
2016-01-20 10:39:24:487 - info: [debug] Could not parse plist file (as binary) at /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/Payload/American-Swan.app/en.lproj/Localizable.strings
2016-01-20 10:39:24:487 - info: Will try to parse the plist file as XML
2016-01-20 10:39:24:488 - info: [debug] Could not parse plist file (as XML) at /var/folders/x0/sdy7g6b57pqf9pwll9zmq7vr0000gn/T/116020-1962-1cnj9tj/Payload/American-Swan.app/en.lproj/Localizable.strings
2016-01-20 10:39:24:488 - warn: Could not parse app Localizable.strings assuming it doesn't exist
2016-01-20 10:39:24:488 - info: [debug] Getting bundle ID from app
2016-01-20 10:39:24:492 - info: [debug] Parsed app Info.plist (as binary)
2016-01-20 10:39:24:492 - info: [debug] Creating instruments
2016-01-20 10:39:24:493 - info: [debug] Preparing uiauto bootstrap
2016-01-20 10:39:24:493 - info: [debug] Dynamic bootstrap dir: /Users/intelligrape/Library/Application Support/appium/bootstrap
2016-01-20 10:39:24:493 - info: [debug] Dynamic env: {"nodePath":"/Applications/Appium.app/Contents/Resources/node/bin/node","commandProxyClientPath":"/Applications/Appium.app/Contents/Resources/node_modules/appium/submodules/appium-uiauto/bin/command-proxy-client.js","instrumentsSock":"/tmp/instruments_sock","interKeyDelay":null,"justLoopInfinitely":false,"autoAcceptAlerts":false,"autoDismissAlerts":false,"sendKeyStrategy":"grouped"}
2016-01-20 10:39:24:501 - info: [debug] Dynamic bootstrap code: // This file is automatically generated. Do not manually modify!
...
2016-01-20 10:39:24:501 - info: [debug] Dynamic bootstrap path: /Users/intelligrape/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
2016-01-20 10:39:24:504 - info: [debug] Reusing dynamic bootstrap: /Users/intelligrape/Library/Application Support/appium/bootstrap/bootstrap-5923cadea0343e3f.js
2016-01-20 10:39:24:507 - info: [debug] Attempting iOS device log capture via libimobiledevice idevicesyslog
2016-01-20 10:39:24:508 - warn: Could not capture device log using libimobiledevice idevicesyslog. Libimobiledevice probably isn't installed
2016-01-20 10:39:24:508 - info: [debug] Attempting iOS device log capture via deviceconsole
2016-01-20 10:39:34:513 - error: Log capture did not start in a reasonable amount of time
2016-01-20 10:39:34:514 - warn: Could not capture logs from device. Continuing without capturing logs.
2016-01-20 10:39:34:514 - info: [debug] Creating iDevice object with udid adff85c69b6404975219f5518d32571545c7b421
2016-01-20 10:39:34:515 - info: [debug] Couldn't find ideviceinstaller, trying built-in at /Applications/Appium.app/Contents/Resources/node_modules/appium/build/libimobiledevice-macosx/ideviceinstaller
2016-01-20 10:39:34:515 - error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
2016-01-20 10:39:34:516 - info: [debug] Cleaning up appium session
2016-01-20 10:39:34:516 - error: Failed to start an Appium session, err was: Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
2016-01-20 10:39:34:520 - info: [debug] Error: Could not initialize ideviceinstaller; make sure it is installed and works on your system
    at [object Object].IOS.getIDeviceObj (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:909:13)
    at [object Object].IOS.installToRealDevice (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:856:32)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:607:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:246:17
    at iterate (/Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:146:13)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:157:25
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:248:21
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/async/lib/async.js:612:34
    at [object Object].<anonymous> (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios.js:1552:14)
    at /Applications/Appium.app/Contents/Resources/node_modules/appium/node_modules/underscore/underscore.js:890:21
    at [object Object]._onTimeout (/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/devices/ios/ios-log.js:166:7)
    at Timer.listOnTimeout (timers.js:119:15)
2016-01-20 10:39:34:521 - info: [debug] Responding to client with error: {"status":33,"value":{"message":"A new session could not be created. (Original error: Could not initialize ideviceinstaller; make sure it is installed and works on your system)","origValue":"Could not initialize ideviceinstaller; make sure it is installed and works on your system"},"sessionId":null}
2016-01-20 10:39:34:523 - info: <-- POST /wd/hub/session 500 11338.296 ms - 300 
2016-01-20 10:39:43:332 - info: --> GET /wd/hub/status {}
2016-01-20 10:39:43:333 - info: [debug] Responding to client with success: {"status":0,"value":{"build":{"version":"1.4.13","revision":"c75d8adcb66a75818a542fe1891a34260c21f76a"}}}

**Comment by Hassan-Radi** [comment]
This is an old defect report, I am gonna close it. Please update to the latest version of Appium server and let me know if the problem still persists.
