### ISSUE TITLE
Unable to launch appium programatically on mac due to missing file appium.js in “Appium.app/Contents/Resources/node_modules/appium/bin/”

### ISSUE THREAD

**Issue by LoveleenSaini** [Genium-Framework/Appium-Support#7]
OS X Version - 10.11.3
Appium 1.5.3
Appium Support - 1.0.5

```
ServerArguments serverArguments = new ServerArguments();
serverArguments.setArgument("--address", "127.0.0.1");
serverArguments.setArgument("--bootstrap-port", 4723);
serverArguments.setArgument("--no-reset", true);
serverArguments.setArgument("--local-timezone", true);
AppiumServer appiumServer = new AppiumServer(serverArguments);
appiumServer.startServer();
```

Failing with error - **com.github.genium_framework.server.exception.InvalidAppiumJSFilePathException: The file you provided was not found on your HDD. You provided the following file path: /Applications/Appium.app/Contents/Resources/node_modules/appium/bin/appium.js**

I have checked and found that appium.js does not exist in .../bin folder on my mac. It doesn't exist in any other folder either.

How can I make it work?

Thanks.

**Comment by Hassan-Radi** [comment]
Did you copy Appium installation files to your Applications folder?

**Comment by LoveleenSaini** [comment]
Yes Appium is there in the Applications folder.
And in "/Applications/Appium.app/Contents/Resources/node_modules/appium/bin/" there is only one file i.e. 'ios-webkit-debug-proxy-launcher.js'

**Comment by Hassan-Radi** [comment]
Please locate the Appium.js file and then use [this](https://github.com/Genium-Framework/Appium-Support/wiki#note-2) to start the server.

**Comment by LoveleenSaini** [comment]
Found the appium.js file in "/Applications/Appium.app/Contents/Resources/node_modules/appium/lib"

I have changed the code as below but it is still failing.

```
AppiumServer appiumServer = new AppiumServer(new File("/Applications/Appium.app/Contents/Resources/node/bin/node"), new File("/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js"), serverArguments);
appiumServer.startServer();
```

Jun 23, 2016 10:44:01 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server is starting...
Jun 23, 2016 10:44:01 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server has not started yet. Trying again in one second...
......
Jun 23, 2016 10:44:30 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server has not started yet. Trying again in one second...

23-06-2016 10:44:31 INFO  - Failed to start Appium server due to following reason: The server didn't start after 30000 milliseconds with error:
/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30000 milliseconds with error:
/Applications/Appium.app/Contents/Resources/node_modules/appium/lib/appium.js:1
(function (exports, require, module, __filename, __dirname) { import _ from 'lodash';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

```
at com.github.genium_framework.appium.support.server.AppiumServer.startServer(AppiumServer.java:298)
at com.github.genium_framework.appium.support.server.AppiumServer.startServer(AppiumServer.java:245)
at Utilities.GeneralFunctionsApp.StartAppiumServer(GeneralFunctionsApp.java:389)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:138)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:277)
at org.testng.SuiteRunner.run(SuiteRunner.java:240)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:72)
at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:122)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

Someone advised to use main.js file instead of appium.js, and I tried that too but it also failed.
https://discuss.appium.io/t/unable-to-launch-appium-programatically-on-mac-due-to-missing-file-appium-js-in-appium-app-contents-resources-node-modules-appium-bin/10725/4

**Comment by Hassan-Radi** [comment]
The correct file path is:

> /Applications/Appium.app/Contents/Resources/node_modules/appium/build/lib/main.js

**Comment by LoveleenSaini** [comment]
It worked fine with the new path.
Thanks for the help.

**Comment by LoveleenSaini** [comment]
Hi @Hassan-Radi 

I have upgraded Appium to version 1.5.3 using nodejs and after that appium server has stopped launching.
(I am not sure if this is a genuine issue so am mentioning the problem here)

**The code:** 

```
ServerArguments serverArguments = new ServerArguments();
serverArguments.setArgument("--address", "127.0.0.1");
serverArguments.setArgument("--bootstrap-port", 4723);
serverArguments.setArgument("--no-reset", true);
serverArguments.setArgument("--local-timezone", true);
AppiumServer appiumServer = new AppiumServer(new File("C:\\Program Files\\nodejs"), new File("C:\\Users\\...\\node_modules\\appium\\build\\lib\\main.js"), serverArguments);        
        appiumServer.startServer();
```

**It fails with following logs:**

Jul 28, 2016 11:38:34 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server is starting...
Jul 28, 2016 11:38:35 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server has not started yet. Trying again in one second...
Jul 28, 2016 11:38:37 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
INFO: Server has not started yet. Trying again in one second...
Jul 28, 2016 11:38:39 AM com.github.genium_framework.appium.support.server.AppiumServer startServer
.
.
.
INFO: Server has not started yet. Trying again in one second...
28-07-2016 11:39:05 INFO - Failed to start Appium server due to following reason: com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30000 milliseconds with error:

com.github.genium_framework.server.exception.ServerTimeoutException: The server didn't start after 30000 milliseconds with error:

**Any idea what could be the issue this time?**
Thanks.

**Comment by Hassan-Radi** [comment]
> new File("C:\Program Files\nodejs")

Should refer to the actual nodejs.exe file not the folder itself.

**Comment by LoveleenSaini** [comment]
Made that change and it is working now.
Thanks.

**Comment by AjatshatruSingh** [comment]
@Hassan-Radi : I am getting the same error on using the appium.js file. As per your suggestion I updated the path to the main.js file but I encountered the below error on the same.

Exception in thread "main" io.appium.java_client.service.local.AppiumServerHasNotBeenStartedLocallyException: The local appium server has not been started. The given Node.js executable: C:\Program Files\nodejs\node.exe Arguments: [D:\Users\ASAJATSH\AppData\Roaming\npm\node_modules\appium\lib\main.js, --port, 4723, --address, 0.0.0.0, --log, D:\Users\ASAJATSH\workspace\Go\appium.log] 
Process output: D:\Users\ASAJATSH\AppData\Roaming\npm\node_modules\appium\lib\main.js:4
import { init as logsinkInit } from './logsink';
^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)


	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:155)
	at com.Astro.common.Base.AstroBaseTest.main(AstroBaseTest.java:37)
Caused by: org.openqa.selenium.net.UrlChecker$TimeoutException: Timed out waiting for [http://0.0.0.0:4723/wd/hub/status] to be available after 120007 ms
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:104)
	at io.appium.java_client.service.local.AppiumDriverLocalService.ping(AppiumDriverLocalService.java:115)
	at io.appium.java_client.service.local.AppiumDriverLocalService.start(AppiumDriverLocalService.java:142)
	... 1 more
Caused by: com.google.common.util.concurrent.UncheckedTimeoutException: java.util.concurrent.TimeoutException
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:143)
	at org.openqa.selenium.net.UrlChecker.waitUntilAvailable(UrlChecker.java:79)
	... 3 more
Caused by: java.util.concurrent.TimeoutException
	at java.util.concurrent.FutureTask.get(Unknown Source)
	at com.google.common.util.concurrent.SimpleTimeLimiter.callWithTimeout(SimpleTimeLimiter.java:130)
	... 4 more


Just for your info: OS: Windows, Appium ver: v1.6.13

**Comment by prateekchawla** [comment]
@Hassan-Radi  Where can i find path for CLI appium installed on my mac

**Comment by pratikbarjatya** [comment]
@prateekchawla  - Type _which appium_ in terminal you will get the location of Appium installation
